name: cache node and NPM dependencies
description: This action allow to cache both Node and NPM dependencies based on the package-lock.json file.
inputs:
  node-version:
    description: NodeJS version to use
    default: 20.x
    required: true
  working-dir:
    description: The working directory of the application
    default: '.'
    required: false

runs:
  using: composite
  steps:
    - name: Setup NodeJS version ${{ input.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ input.node-version }}
    - name: cache dependencies
      id: cache
      uses: actions/cached@v3
      with:
        path: ${{ inputs.working-dir }}/node_modules
        key: node-modules-${{ hashFiles('${{ inputs.working-dir }}/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cahce-hit != 'true'
      run: npm ci
      shell: bash
      working-directory: ${{ inputs.working-dir }}