name: 02-workflow-events
on: 
  workflow_dispatch: 
  #push:
  # pull_request: #pull request made or creating branch
  # schedule:
  #   - cron: '*/3 * * * *'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "Event name ${{ github.event_name }}"