name: my first workflow
on: create
    #push

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Hello
              run: echo "Hello World"
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: failing step
              run: |
                echo "I will fail"
                exit 1
            - name: say goodbye
              run: echo "Good bye"
    