name: 02 Workflow Events
on:
  push:
  pull_request:
  schedule:
    - cron: '0/3 * * * *'
  workflow_dispatch:
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "Its triggered by ${{ github.event_name }}"
            