name: 02 Workflow Events
on:
  #push:
  pull_request:
  #schedule:
  #  - cron: '* * * * *'
  workflow_dispatch: 
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "Its triggered by ${{ github.event_name }}"
            