name: 15 - Working with Matrices
on:
    push:
    workflow_dispatch:
jobs:
    backwards-compatibility:
        name: ${{ matrix.OS }}-${{ matrix.node-version }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version:
                    - 18.x
                    - 20.x
                    - 21.x
                OS:
                    - ubuntu-lates
                    - windows-latest
        steps:
            - name: setup node
              uses: actions/setup-node@v3
              with: 
                node-version: ${{ matrix.node-version }}
            - name: Perform some test
              run: echo "Running tests on OS - ${{ matrix.OS }} and NodeJS ${{ matrix.node-version }}"