name: 16 - Working with Environments
on:
    push:
    workflow_dispatch:
        inputs:
            target-env:
                type: environment
                default: staging
jobs:
    echo:
        runs-on: ubuntu-latest
        environment: ${{ inputs.target-env }}
        env:
            my-env-value: ${{ vars.MY_VAR2 || 'default' }}
        steps:
            - name: echo vars
              run: |
                echo "Env variable: ${{ env.my-env-value }}"