name: MY NPM package workflow
on: 
  push:
    branches:
      - '*''
    branches-ignore: 
      - 'main'
jobs:
  node-16-tests:
    runs-on: ubuntu-latest
    steps:
      - name: node setup
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm test